apiVersion: v1
kind: Secret
data:
  config.yaml: ImF1dGhvcml6YXRpb24iOgogICJzdGF0aWMiOgogIC0gInBhdGgiOiAiL21ldHJpY3MiCiAgICAicmVzb3VyY2VSZXF1ZXN0IjogZmFsc2UKICAgICJ1c2VyIjoKICAgICAgIm5hbWUiOiAic3lzdGVtOnNlcnZpY2VhY2NvdW50Om9wZW5zaGlmdC1vYnNlcnZhYmlsaXR5LW9wZXJhdG9yOmh5cGVyc2hpZnQtbW9uaXRvcmluZy1zdGFjay1wcm9tZXRoZXVzIgogICAgInZlcmIiOiAiZ2V0Igo=
metadata:
  labels:
  name: ethtool-exporter-kube-rbac-proxy-config
  namespace: openshift-sre-ethtool-exporter
type: Opaque
